version: "3.9"

services:
  mysql-db:
    image: mysql:latest
    container_name: service-database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: archetypedb
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: password_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: archetype-java-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/archetypedb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user_dev
      - SPRING_DATASOURCE_PASSWORD=password_dev
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data: