# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
  servlet:
    context-path: /archetype-service
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: DEC(your_username)
    password: DEC(your_password)
    server:
      protocol: smtp
      debug: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8
    cache: false
  application:
    name: archetype-service
  main.banner-mode: off
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/archetypedb
    username: ENC(8gbqvhYTfYgLSMqysc2AQmvgiZEeMRtP7XNdNvALyI6Yrf2XtB0Oy6wtPYkI6BM2)
    password: ENC(G1S58A3F6ykIQtSqAVnETEzVNbK93XOHAkIUStbJRvZldzLilF5FHck9mrCpx2YK)
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline: 0

  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    key: ENC(tK6tWdtYuqyC0G4Xcfe1zhiDt+dnXnbBprtLfOKnMSsX1ze5IBfvsZeiJ29wo/sYJTjj5TJQ6j05UTlxjgulCFAuJ9NAHJiIeotWMu4lgsoh7mpUzS9ESfrfbctc+gObjd767RQvBZfXjccelTGINA==)
    lifeTime: 631138000000
    refreshLifeTime: 631138000000
  cors:
    origins:
      http://127.0.0.1:4200,
      http://localhost:4200,
      http://localhost:4201
# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  pattern:
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
    console: "%p [${spring.application.name:}, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %m%n%ex{3}"
  level:
    com.moontech: DEBUG
    org:
      springframework.data: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

# ===================================================================
# URL ENDPOINTS
# ===================================================================
api:
  uri:
    domain:
      users: /users
    data:
      modified: /{id}
      authentication: ${api.uri.domain.users}/authentication
      confirm: ${api.uri.domain.users}/confirm
      userConfirm: /confirm
      reset: /password/reset
      passwordForgot: ${api.uri.domain.users}/password/reset
  interceptorPath: "/**"
  # ===================================================================
  # MAIL TEMPLATE PROPERTIES
  # ===================================================================
  mail:
    templates:
      user: email-user-template.flth
      customer: email-customer-template.flth
      payment: email-payment-subscription-template.flth
      forgot_password: forgot-password-template.flth
      reset_password: reset_password_template.flth
    from: DEC(your email)
    welcomeSubject: Bienvenido
    forgotPasswordSubject: Recupera tu Contraseña
    resetPasswordSubject: Tu contraseña ha sido cambiada
    enterpriseName: Enterprise-Name
    supportEmail: support@enterprise.com
# ===================================================================
# GEOIP PROPERTIES
# ===================================================================
geoip:
  db-path: classpath:geolocation/GeoLite2-City.mmdb

# ===================================================================
# SWAGGER PROPERTIES
# ===================================================================
swagger:
  basePackage: com.moontech
  title: SERV-archetype-java-service
  descriptionApi: Archetype java service
  version: 1.0.0
  nameDeveloper: Felipe Monzón
  contactUrl: https://felipemonzon.github.io/
  emailDeveloper: felipemonzon2705@gmail.com
  licenceType: MIT LICENCE
  licenceUrl: https://github.com/felipemonzon/archetype-java-service/blob/main/LICENSE
